# Generated by Django 5.2 on 2025-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_answer_created_at_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ranking_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='yesno_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('rating', 'Rating'), ('yesno', 'Yes/No'), ('ranking', 'Ranking')], max_length=10),
        ),
    ]
