# Generated by Django 5.2 on 2025-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_answer_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('rating', 'Rating'), ('yesno', 'Yes/No'), ('ranking', 'Ranking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
